Make installable via cocoapods on iOS and added support for promises, updating to use non deprecated methods.
robertbarclay/react-native-immediate-phone-call pull request #1
Opened 2019-10-03 17:19 UTC by robertbarclay

2019-10-03 17:30 UTC, TylerWhitman commented on android/src/main/java/com/github/wumke/RNImmediatePhoneCall/RNImmediatePhoneCallModule.java
> +            Bool hasPermission = ContextCompat.checkSelfPermission(reactContext.getApplicationContext(),
Dont think there is Bool in java, should be Boolean. https://docs.oracle.com/javase/8/docs/api/index.html?java/lang/Boolean.html

2019-10-03 17:30 UTC, TylerWhitman commented on android/src/main/java/com/github/wumke/RNImmediatePhoneCall/RNImmediatePhoneCallModule.java
> +            Bool hasPermission = ContextCompat.checkSelfPermission(reactContext.getApplicationContext(),
Unless this is some custom object?

2019-10-03 17:33 UTC, TylerWhitman commented on android/src/main/java/com/github/wumke/RNImmediatePhoneCall/RNImmediatePhoneCallModule.java
> +    private static void call(String number, Promise promise, Activity activity) {
Do you need to resolve the promise?

2019-10-10 17:04 UTC, jimmyfortinx requested changes

2019-10-10 17:04 UTC, jimmyfortinx commented on index.js
> +            return NativeModules.RNImmediatePhoneCall.immediatePhoneCall("411");
Hardcoded 411 here

2019-10-10 17:04 UTC, jimmyfortinx commented on index.js
> +    return NativeModules.RNImmediatePhoneCall.immediatePhoneCall("411");
Hardcoded 411 here too

2019-10-10 17:04 UTC, jimmyfortinx commented on index.js
> +    }
```suggestion
    return granted === PermissionsAndroid.RESULTS.GRANTED;
```

2019-10-10 17:04 UTC, jimmyfortinx commented on index.js
> +    return false;
I'm not sure about removing the error... This could hide something important to the user that will use this lib.

2019-10-11 13:27 UTC, closed without merging